name: local_storage_activities_api
description: A Flutter implementation of the ActivitiesApi that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  activities_api:
    path: ../activities_api
  flutter:
    sdk: flutter
  meta: ^1.8.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
