name: activities_repository
description: A repository that handles activity related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
    
dependencies:
  activities_api:
    path: ../activities_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
